# Generated by Django 5.2 on 2025-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_alter_sonnenschutzfaktor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperaturkorrekturfaktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauteil', models.CharField(help_text="Name des Bauteils (z. B. 'Außenwand, Fenster, Decke über Außenluft' o.ä.)", max_length=200, unique=True)),
                ('fx', models.FloatField(help_text='Temperaturkorrekturfaktor Fx (z. B. 1.0, 0.8, 0.35 …)')),
            ],
        ),
    ]
