# Generated by Django 5.2 on 2025-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_alter_solarstrahlungmonat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonneneintragsKennwert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('S1', 'S1 (Nachtlüftung + Bauart)'), ('S2', 'S2 (Fensterflächenanteil)'), ('S3', 'S3 (Sonnenschutzglas)'), ('S4', 'S4 (Fensterneigung)'), ('S5', 'S5 (Orientierung)'), ('S6', 'S6 (Passive Kühlung)')], max_length=2)),
                ('kennwert_key', models.CharField(help_text="z.B. 'S1_ohne_leicht', 'S6_schwer' etc.", max_length=20, unique=True)),
                ('beschreibung', models.CharField(max_length=100)),
                ('bauart', models.CharField(blank=True, help_text="Nur für S1 und S6: 'leicht', 'mittel', 'schwer'", max_length=10, null=True)),
                ('wohng_A', models.FloatField(blank=True, help_text='Wohngebäude, Klimaregion A', null=True)),
                ('wohng_B', models.FloatField(blank=True, help_text='Wohngebäude, Klimaregion B', null=True)),
                ('wohng_C', models.FloatField(blank=True, help_text='Wohngebäude, Klimaregion C', null=True)),
                ('nw_A', models.FloatField(blank=True, help_text='Nichtwohngebäude, Klimaregion A', null=True)),
                ('nw_B', models.FloatField(blank=True, help_text='Nichtwohngebäude, Klimaregion B', null=True)),
                ('nw_C', models.FloatField(blank=True, help_text='Nichtwohngebäude, Klimaregion C', null=True)),
            ],
            options={
                'verbose_name': 'Sonneneintragskennwert',
                'verbose_name_plural': 'Sonneneintragskennwerte',
                'unique_together': {('kennwert_key',)},
            },
        ),
    ]
