# Generated by Django 5.2 on 2025-06-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0007_sonneneintragskennwert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sonneneintragskennwert',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='bauart',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='kennwert_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='nw_A',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='nw_B',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='nw_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='typ',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='wohng_A',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='wohng_B',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='wohng_C',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
