# Generated by Django 5.2 on 2025-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0009_alter_sonneneintragskennwert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bauteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laenge', models.FloatField(blank=True, null=True)),
                ('breite', models.FloatField(blank=True, null=True)),
                ('geschosshoehe', models.FloatField(blank=True, null=True)),
                ('anz_geschosse', models.IntegerField(blank=True, null=True)),
                ('u_wand_nord', models.FloatField(blank=True, null=True)),
                ('u_wand_sued', models.FloatField(blank=True, null=True)),
                ('u_wand_west', models.FloatField(blank=True, null=True)),
                ('u_wand_ost', models.FloatField(blank=True, null=True)),
                ('u_bodenplatte', models.FloatField(blank=True, null=True)),
                ('u_dach', models.FloatField(blank=True, null=True)),
                ('hoehe', models.FloatField(blank=True, null=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('bgf', models.FloatField(blank=True, null=True)),
                ('nf', models.FloatField(blank=True, null=True)),
                ('ne_absolut', models.FloatField(blank=True, null=True)),
                ('ne_spez', models.FloatField(blank=True, null=True)),
                ('sb_absolut', models.FloatField(blank=True, null=True)),
                ('sb_spez', models.FloatField(blank=True, null=True)),
                ('wb_absolut', models.FloatField(blank=True, null=True)),
                ('ee_absolut', models.FloatField(blank=True, null=True)),
                ('ee_spez', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
