# Generated by Django 5.2 on 2025-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0010_bauteil'),
    ]

    operations = [
        migrations.AddField(
            model_name='bauteil',
            name='laufzeit_da',
            field=models.FloatField(blank=True, null=True, verbose_name='Betriebstage d/a'),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='laufzeit_hd',
            field=models.FloatField(blank=True, null=True, verbose_name='Betriebsstunden h/d'),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='lueftungstyp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lüftungstyp'),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='luftwechselrate',
            field=models.FloatField(blank=True, null=True, verbose_name='Luftwechselrate (1/h)'),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='raum_temp_soll',
            field=models.FloatField(blank=True, null=True, verbose_name='Raum-Soll-Temperatur (°C)'),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='wrg_wirkungsgrad',
            field=models.FloatField(blank=True, null=True, verbose_name='WRG-Wirkungsgrad (%)'),
        ),
    ]
