# Generated by Django 5.2 on 2025-06-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0012_bauteil_lb_absolut_bauteil_lb_spezifisch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bauteil',
            name='laufzeit_da',
            field=models.FloatField(blank=True, help_text='Betriebszeit pro Jahr (d/a)', null=True),
        ),
        migrations.AlterField(
            model_name='bauteil',
            name='laufzeit_hd',
            field=models.FloatField(blank=True, help_text='Betriebszeit pro Tag (h/d)', null=True),
        ),
        migrations.AlterField(
            model_name='bauteil',
            name='lueftungstyp',
            field=models.CharField(blank=True, help_text='Art der Lüftung (z.B. dezentral, zentral)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bauteil',
            name='luftwechselrate',
            field=models.FloatField(blank=True, help_text='Luftwechselrate (1/h)', null=True),
        ),
        migrations.AlterField(
            model_name='bauteil',
            name='raum_temp_soll',
            field=models.FloatField(blank=True, help_text='Soll-Temperatur im Raum (°C)', null=True),
        ),
        migrations.AlterField(
            model_name='bauteil',
            name='wrg_wirkungsgrad',
            field=models.FloatField(blank=True, help_text='Wirkungsgrad der Wärmerückgewinnung (%)', null=True),
        ),
    ]
