# Generated by Django 5.2 on 2025-06-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DruckverlustBauteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauteil', models.CharField(help_text="Name des Bauteils (z. B. 'Erhitzer', 'Kühler' usw.)", max_length=100, unique=True)),
                ('druckverlust_pa', models.PositiveIntegerField(help_text='Druckverlust (Pa) bei Normalzustand')),
            ],
        ),
    ]
