# Generated by Django 5.2 on 2025-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_temperaturkorrekturfaktor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturkorrekturfaktor',
            name='bauteil',
            field=models.CharField(help_text="Name des Bauteils (z. B. 'Außenwand, Fenster, Decke über Außenluft').", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='temperaturkorrekturfaktor',
            name='fx',
            field=models.FloatField(help_text='Temperaturkorrekturfaktor Fx (z. B. 1.0, 0.8, 0.35 …).'),
        ),
    ]
