# Generated by Django 5.2 on 2025-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_alter_temperaturkorrekturfaktor_bauteil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarstrahlungmonat',
            options={'verbose_name': 'Solare Strahlung pro Monat', 'verbose_name_plural': 'Solare Strahlung'},
        ),
        migrations.AlterUniqueTogether(
            name='solarstrahlungmonat',
            unique_together={('orientierung', 'neigung')},
        ),
        migrations.AddField(
            model_name='solarstrahlungmonat',
            name='maerz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='apr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='aug',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='dez',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='feb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='jahreswert',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='jan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='jul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='jun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='neigung',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='nov',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='okt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='orientierung',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solarstrahlungmonat',
            name='sep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='solarstrahlungmonat',
            name='maer',
        ),
        migrations.RemoveField(
            model_name='solarstrahlungmonat',
            name='region_id',
        ),
    ]
