# Generated by Django 5.2 on 2025-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0008_alter_sonneneintragskennwert_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sonneneintragskennwert',
            options={'ordering': ['typ', 'bauart', 'kennwert_key'], 'verbose_name': 'Sonneneintragskennwert', 'verbose_name_plural': 'Sonneneintragskennwerte'},
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='kennwert_key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sonneneintragskennwert',
            name='typ',
            field=models.CharField(max_length=10),
        ),
    ]
